services:
  vue-subdir-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-subdir-app
    networks:
      - gateway-network
    restart: unless-stopped

networks:
  gateway-network:
    external: true
